#### Inputs for data #####
#Output directory
path : 'output_simulations'

#Time step
dt : 0.02

#Number of species
Nspecies : 50
Nextra : 20

#Initial conditions
x0 : np.full(Nspecies, 1./Nspecies)

#Growth rates
r : 1.0

#Interaction matrix
mu: -2.
sigma: 1.6
sigma_env2: 0.1

#Number of realizations
Nreal : 1 

#Number of steps of each realization
Nprint :  1

#Number of steps of each realization
Nsteps :  1000

#Parameters for extra species
mu_extra : 1.e-3
sigma2_extra : 1.e-4

